export const REQUEST_CARD = 'REQUEST_CARD';
export const RECEIVE_CARD = 'RECEIVE_CARD';
export const UPDATE_CARD = 'UPDATE_CARD';
export const SAVE_CARD = 'SAVE_CARD';
export const ERROR_RECEIVE_CARD = 'ERROR_RECEIVE_CARD';